### ISSUE TITLE
How can I change the model between real control and fake control?

### ISSUE THREAD

**Issue by CaffeMrDe** [ros-industrial/industrial_core#255]
I already write the robot real control sucessfully. And how can I run the fake control and real control at the same time? 

ros platform: kinetic

**Comment by gavanderhoorn** [comment]
I'm not sure I completely understand your question.

I'm also wondering whether this would not be better posted at `answers.ros.org`, as it doesn't seem like you're reporting an issue with any of the packages in this repository.

Until you've clarified this, I'm going to assume it's more of a usage/configuration question and close it here.

Feel free to keep commenting on it of course, and if it turns out this is actually an issue that belongs here, we'll reopen.
