### ISSUE TITLE
Migrate moveIt packages to moveit_simple_controller_manager

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_core#3]
MoveIt users have recently released a new controller manager plugin: moveit_simple_controller_manager, intended to be used for robots that do not require complex controller_manager capabilities.

Currently, we use the pr2_controller_manager, with the parameter use_controller_manager set to false. This new plugin would be a cleaner solution, and would reduce an unnecessary dependency on pr2 packages.

We should update the existing moveIt packages and the ROS-I wiki documentation to use this new plugin.

**Comment by gavanderhoorn** [comment]
Seems the `pr2_controller_manager` cannot be used anymore in MoveIt configs (or at least, MoveIt has started complaining on my machine since earlier this week). I've got something that works locally, using the MoveIt simple_controller_manager, but I'm not quite sure that it's up-to-scratch.

If someone with some more insight could take a look at this? And preferably update the tutorial as well?

**Comment by JeremyZoss** [comment]
Wiki documentation is updated.  See [here](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot#Update_Configuration_Files).  I think I have patches submitted for all relevant robot packages.  We can close this when those patches (linked to this issue) are accepted.

**Comment by gavanderhoorn** [comment]
@JeremyZoss: right, that was how I did it for my Fanuc configs as well. Thanks.

**Comment by gavanderhoorn** [comment]
Fixed `fanuc_experimental` packages with ros-industrial/fanuc_experimental#2.

**Comment by shaun-edwards** [comment]
Fixed, closed.
