### ISSUE TITLE
Dynamic number of joints in joint streaming interface

### ISSUE THREAD

**Issue by JMLambert** [ros-industrial/industrial_core#40]
Currently, the number of joint-related information that can be transmitted by the joint streaming interface is hard-coded. Being able to specify the number of joint information that can be passed dynamically would greatly increase flexibility of the interface.

**Comment by gavanderhoorn** [comment]
@JMLambert: could you elaborate a bit on what you mean exactly by "_the number of joint-related information_"? Are you talking about the number of joints reported on, or about the _types_ of information (ie: joint angles, velocities, etc)?

**Comment by JMLambert** [comment]
Sure, I'm talking about the number of joints for which you can send information (I agree, that was a bit cryptic). Right now, you can only send info for a maximum of 10 joints. If your robot(s) have more joints, you have to change that hard-coded limit and recompile simple_message as well as industrial_robot_client. I'D be nice to be able to set this dynamically.

**Comment by shaun-edwards** [comment]
@JMLambert, we discussed this offline, but I am adding that part of the discussion to this issue.

As far as future plans, the message has to remain relatively static in order to ensure backwards compatibility.  This is one of the downfalls of running an open source project, any changes we make have to take others into consideration.  Instead of modifying the current message, we plan to create a new group of dynamic messages that can take a varying number of joints (see: https://github.com/ros-industrial/rep/blob/master/rep-I0001.rst ).  If/when this REP is implemented, a new simple message type would be created that could address your problem.
