### ISSUE TITLE
simple_message: Missing BYTE_SWAPPING target_property in utest declaration?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_core#56]
Excerpts from the `CMakeLists.txt` in `simple_message`:

_target_properties_ for endianness swapping utest:

> set_target_properties(utest_byte_swapping PROPERTIES COMPILE_DEFINITIONS "TEST_PORT_BASE=12000")

target_properties for float64 utest:

> set_target_properties(utest_float64 PROPERTIES COMPILE_DEFINITIONS "TEST_PORT_BASE=13000;FLOAT64")

The float64 version repeats the `FLOAT64` define in the test target_properties, the byte swapping version does not (no `BYTE_SWAPPING` in target_properties).

I haven't looked at the actual execution paths influenced by these defines, but is this an omission? Should the utest target_properties for byte swapping also include the define?

**Comment by shaun-edwards** [comment]
As it turns out the `BYTE_SWAPPING` macro affects only the source code(i.e. *.cpp files).  This means that the byte/byte_swapping variations of the library do not need an additional macro definitions in executables/libraries that link to them.

`FLOAT64` affects both the source code and the header files, [shared_types.h](https://github.com/ros-industrial/industrial_core/blob/hydro-devel/simple_message/include/simple_message/shared_types.h).  As a result the macro must be included in any executable/library the links to the `FLOAT64` library.  This is not ideal, since forgetting to include the macro definition could lead to ugly/hard to find bugs.  This is not a critical issue, but one that we may want to address in a future release.

**Comment by gavanderhoorn** [comment]
Right, similar to the `INT32` and `INT64` defines, I see.

In similar situations it's customary to provide a `config.h` header file, which contains the appropriate set of defines used in building the library. This could then be included in `simple_message.h` (or some other required header). That would remove the need to export those defines from our source package. CMake has some infrastructure that can be used to generate such config files (`configure_file(..)` fi). This would then be used in combination with the _configuration packages_ discussed in #46.

Another option would be to use the `catkin_package(.. CFG_EXTRAS ..)` parameter, as used in #46.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:

>  This is not a critical issue, but one that we may want to address in a future release.

Are we keeping this issue open because of that? Perhaps we should create some new ones to track these specific problems.

This one could be closed: `BYTE_SWAPPING` is not missing.
